search_terms = [
    "Minecraft tutorial",
    "Fortnite gameplay",
    "Apex Legends tips",
    "Call of Duty multiplayer",
    "League of Legends",
    "Overwatch gameplay",
    "GTA V walkthrough",
    "The Legend of Zelda: Breath of the Wild review",
    "Super Smash Bros. Ultimate tournaments",
    "FIFA 22 career mode",
    "Assassin's Creed Valhalla secrets",
    "World of Warcraft raid guide",
    "Valorant tips and tricks",
    "Cyberpunk 2077 character customization",
    "Rocket League gameplay",
    "Pokemon Sword and Shield let's play",
    "Battlefield V multiplayer",
    "Destiny 2 raids",
    "Fall Guys funny moments",
    "Among Us strategy",
    "The Witcher 3: Wild Hunt walkthrough",
    "Resident Evil Village boss fights",
    "Animal Crossing: New Horizons island design",
    "Hearthstone deck building",
    "Super Mario Odyssey speedrun",
    "PlayerUnknown's Battlegrounds tactics",
    "The Last of Us Part II gameplay",
    "Dota 2 tournament highlights",
    "Counter-Strike: Global Offensive weapon skins",
    "Warframe beginner's guide",
    "Madden NFL 22 gameplay",
    "Borderlands 3 legendary weapons",
    "Dead by Daylight survivor tips",
    "Rainbow Six Siege ranked matches",
    "Final Fantasy XIV class guide",
    "Among Us live stream",
    "The Elder Scrolls V: Skyrim mods",
    "Fortnite dances",
    "Mortal Kombat 11 fatalities",
    "Farming Simulator 22 gameplay",
    "Sea of Thieves treasure hunting",
    "Pokémon GO raid battles",
    "Valorant agent guide",
    "Dark Souls III boss strategies",
    "Street Fighter V combo tutorials",
    "Stardew Valley farm layout ideas",
    "Marvel's Spider-Man: Miles Morales gameplay",
    "Rust base building",
    "Tom Clancy's Ghost Recon Breakpoint stealth tactics",
    "NBA 2K22 MyCareer mode",
    "Resident Evil 2 remake walkthrough",
    "Sekiro: Shadows Die Twice boss fights",
    "ARK: Survival Evolved dinosaur taming",
    "World of Warcraft: Shadowlands dungeon guide",
    "Rainbow Six Siege operator tips",
    "Grand Theft Auto Online heists",
    "Fallout 4 settlement building",
    "Red Dead Redemption 2 hunting tips",
    "Phasmophobia gameplay",
    "Assassin's Creed Odyssey exploration",
    "The Sims 4 building",
    "Super Smash Bros. Ultimate character analysis",
    "Path of Exile build guide",
    "Fortnite Battle Pass rewards",
    "Monster Hunter: World weapon tutorials",
    "Cuphead boss strategies",
    "Dead Cells speedrun",
    "Minecraft redstone creations",
    "Tom Clancy's The Division 2 endgame content",
    "Among Us impostor tactics",
    "League of Legends champion spotlight",
    "Genshin Impact character showcase",
    "Apex Legends weapon tier list",
    "The Legend of Zelda: Skyward Sword HD review",
    "PlayerUnknown's Battlegrounds sniping tips",
    "Madden NFL 22 franchise mode",
    "No Man's Sky base building",
    "The Witcher 3: Wild Hunt best armor",
    "Ratchet & Clank: Rift Apart gameplay",
    "FIFA 22 Ultimate Team tips",
    "Fall Guys strategies",
    "World of Warcraft leveling guide",
]