search_terms = [
    # "Minecraft tutorial",
#     "Fortnite gameplay",
#     "Apex Legends tips",
#     "Call of Duty multiplayer",
#     "League of Legends",
#     "Overwatch gameplay",
#     "GTA V walkthrough",
#     "The Legend of Zelda: Breath of the Wild review",
#     "Super Smash Bros. Ultimate tournaments",
#     "FIFA 22 career mode",
#     "Assassin's Creed Valhalla secrets",
#     "World of Warcraft raid guide",
#     "Valorant tips and tricks",
#     "Cyberpunk 2077 character customization",
#     "Rocket League gameplay",
#     "Pokemon Sword and Shield let's play",
#     "Battlefield V multiplayer",
#     "Destiny 2 raids",
#     "Fall Guys funny moments",
#     "Among Us strategy",
#     "The Witcher 3: Wild Hunt walkthrough",
#     "Resident Evil Village boss fights",
#     "Animal Crossing: New Horizons island design",
#     "Hearthstone deck building",
#     "Super Mario Odyssey speedrun",
#     "PlayerUnknown's Battlegrounds tactics",
#     "The Last of Us Part II gameplay",
#     "Dota 2 tournament highlights",
#     "Counter-Strike: Global Offensive weapon skins",
#     "Warframe beginner's guide",
#     "Madden NFL 22 gameplay",
#     "Borderlands 3 legendary weapons",
#     "Dead by Daylight survivor tips",
#     "Rainbow Six Siege ranked matches",
#     "Final Fantasy XIV class guide",
#     "Among Us live stream",
#     "The Elder Scrolls V: Skyrim mods",
#     "Fortnite dances",
#     "Mortal Kombat 11 fatalities",
#     "Farming Simulator 22 gameplay",
#     "Sea of Thieves treasure hunting",
#     "Pokémon GO raid battles",
#     "Valorant agent guide",
#     "Dark Souls III boss strategies",
#     "Street Fighter V combo tutorials",
#     "Stardew Valley farm layout ideas",
#     "Marvel's Spider-Man: Miles Morales gameplay",
#     "Rust base building",
#     "Tom Clancy's Ghost Recon Breakpoint stealth tactics",
#     "NBA 2K22 MyCareer mode",
#     "Resident Evil 2 remake walkthrough",
#     "Sekiro: Shadows Die Twice boss fights",
#     "ARK: Survival Evolved dinosaur taming",
#     "World of Warcraft: Shadowlands dungeon guide",
#     "Rainbow Six Siege operator tips",
#     "Grand Theft Auto Online heists",
#     "Fallout 4 settlement building",
#     "Red Dead Redemption 2 hunting tips",
#     "Phasmophobia gameplay",
#     "Assassin's Creed Odyssey exploration",
#     "The Sims 4 building",
#     "Super Smash Bros. Ultimate character analysis",
#     "Path of Exile build guide",
#     "Fortnite Battle Pass rewards",
#     "Monster Hunter: World weapon tutorials",
#     "Cuphead boss strategies",
#     "Dead Cells speedrun",
#     "Minecraft redstone creations",
#     "Tom Clancy's The Division 2 endgame content",
#     "Among Us impostor tactics",
#     "League of Legends champion spotlight",
#     "Genshin Impact character showcase",
#     "Apex Legends weapon tier list",
#     "The Legend of Zelda: Skyward Sword HD review",
#     "PlayerUnknown's Battlegrounds sniping tips",
#     "Madden NFL 22 franchise mode",
#     "No Man's Sky base building",
#     "The Witcher 3: Wild Hunt best armor",
#     "Ratchet & Clank: Rift Apart gameplay",
#     "FIFA 22 Ultimate Team tips",
#     "Fall Guys strategies",
#     "World of Warcraft leveling guide",
#         "Fortnite item shop",
#     "Call of Duty Warzone loadout",
#     "Minecraft speedrun",
#     "Overwatch hero guides",
#     "Animal Crossing: New Horizons turnip prices",
#     "League of Legends eSports",
#     "Valorant ranked matches",
#     "GTA V cheat codes",
#     "Apex Legends character abilities",
#     "Assassin's Creed Valhalla hidden secrets",
#     "The Elder Scrolls Online PvP",
#     "FIFA 22 skill moves tutorial",
#     "Halo Infinite gameplay",
#     "Cyberpunk 2077 best builds",
#     "Monster Hunter Rise armor sets",
#     "Super Mario Maker 2 level showcase",
#     "Rainbow Six Siege operator loadouts",
#     "Among Us mod showcase",
#     "Pokémon Sword and Shield competitive battles",
#     "World of Warcraft gold farming",
#     "Rocket League trading",
#     "NBA 2K22 MyTeam mode",
#     "Resident Evil Village puzzle solutions",
#     "Mortal Kombat 11 character breakdowns",
#     "Fallout 76 base building tips",
#     "Sea of Thieves PvP encounters",
#     "The Sims 4 expansion pack reviews",
#     "Destiny 2 exotic weapon quests",
#     "Valorant map callouts",
#     "Final Fantasy VII Remake boss strategies",
#     "Stardew Valley fishing guide",
#     "Minecraft survival tips",
#     "Genshin Impact world exploration",
#     "Apex Legends sniping spots",
#     "The Legend of Zelda: Breath of the Wild secrets",
#     "FIFA 22 career mode wonderkids",
#     "Warframe prime warframes",
#     "Assassin's Creed Origins historical accuracy",
#     "The Witcher 3: Wild Hunt side quests",
#     "Fortnite creative mode showcases",
#     "Call of Duty zombies easter eggs",
#     "Pokémon Unite gameplay",
#     "Dota 2 hero spotlight",
#     "Super Smash Bros. Ultimate tier list",
#     "Tom Clancy's Ghost Recon Breakpoint weapon customization",
#     "Red Dead Redemption 2 legendary animals",
#     "Minecraft mods showcase",
#     "Sekiro: Shadows Die Twice speedrun",
#     "Phasmophobia ghost types",
#     "Borderlands 3 boss farming",
#     "ARK: Survival Evolved base defense strategies",
#     "Among Us venting tactics",
#         "Super Mario 64 speedrun",
#     "The Legend of Zelda: Ocarina of Time walkthrough",
#     "Final Fantasy VII Remake review",
#     "Kingdom Hearts lore explained",
#     "Resident Evil 4 gameplay",
#     "Metal Gear Solid boss fights",
#     "Crash Bandicoot N. Sane Trilogy gameplay",
#     "Spyro the Dragon secrets",
#     "Pokemon Red and Blue nostalgia",
#     "GoldenEye 007 multiplayer",
#     "Gran Turismo 2 car tuning",
#     "Sonic the Hedgehog speedrun",
#     "Tomb Raider puzzle solutions",
#     "Street Fighter II combo tutorials",
#     "Super Smash Bros. Melee competitive scene",
#     "Jak and Daxter: The Precursor Legacy let's play",
#     "Tony Hawk's Pro Skater soundtrack",
#     "Silent Hill atmosphere analysis",
#     "Legend of Mana hidden treasures",
#     "Final Fantasy Tactics job guide",
#     "Kingdom Hearts boss strategies",
#     "Resident Evil 2 (1998) playthrough",
#     "Crash Team Racing shortcuts",
#     "Soulcalibur character creation",
#     "Metal Gear Solid storyline explained",
#     "Pokemon Stadium mini-games",
#     "Gran Turismo 3 A-Spec license tests",
#     "The Legend of Zelda: Majora's Mask secrets",
#     "Super Mario Sunshine 100% completion",
#     "Final Fantasy IX character analysis",
#     "Kingdom Hearts secret endings",
#     "Resident Evil Code: Veronica plot summary",
#     "Tekken 3 combo breakdowns",
#     "Metal Gear Solid 2: Sons of Liberty gameplay",
#     "Crash Nitro Kart multiplayer races",
#     "Shadow of the Colossus boss strategies",
#     "Resident Evil 3: Nemesis (1999) walkthrough",
#     "Final Fantasy X best sphere grid paths",
#     "Kingdom Hearts 2.5 Remix cutscene compilation",
#     "Mario Kart 64 shortcut guide",
#     "Tekken Tag Tournament character tier list",
#    "Super Mario World speedrun",
#     "The Legend of Zelda: A Link to the Past walkthrough",
#     "Final Fantasy VI best party composition",
#     "Kingdom Hearts 3 secret boss guide",
#     "Resident Evil (1996) mansion exploration",
#     "Chrono Trigger time travel mechanics",
#     "Crash Bandicoot 2: Cortex Strikes Back secrets",
#     "Metal Gear Solid 3: Snake Eater story analysis",
#     "Tekken 7 combo tutorials",
#     "Silent Hill 2 psychological horror analysis",
#     "Final Fantasy VIII Triple Triad strategies",
#     "Mario Kart: Double Dash!! character combinations",
#     "The Legend of Zelda: Wind Waker HD boss battles",
#     "Jak II open-world exploration",
#     "Shadow of the Colossus soundtrack appreciation",
#     "Resident Evil 4 weapon upgrades",
#     "Kingdom Hearts Birth by Sleep character backstories",
#     "Crash Bandicoot: Warped time trials",
#     "Final Fantasy VII original vs. remake comparison",
#     "Metal Gear Solid 4: Guns of the Patriots cutscene compilation",
#     "Tekken Tag Tournament 2 online tournaments",
#     "Donkey Kong Country secrets and hidden levels",
#     "Resident Evil 7: Biohazard VR experience",
#     "Super Mario RPG: Legend of the Seven Stars boss strategies",
#     "The Legend of Zelda: Skyward Sword HD controls guide",
#     "Final Fantasy XII hunts and rare game locations",
#     "Kingdom Hearts II final mix+ secret endings",
#     "Crash Bandicoot: The Wrath of Cortex gameplay",
#     "Metal Gear Solid V: The Phantom Pain base management tips",
#     "Tekken 5 character movelist breakdowns",
#     "Silent Hill 3 symbolism analysis",
#     "Final Fantasy Tactics Advance job combinations",
#     "Mario Party mini-games compilation",
#     "The Legend of Zelda: Twilight Princess HD hidden easter eggs",
#     "Resident Evil Remake puzzle solutions",
#     "Kingdom Hearts Re:Chain of Memories deck building strategies",
#     "Crash Bash multiplayer party mode",
#     "Metal Gear Solid Portable Ops storyline recap",
#     "Tekken 6 customization options",
#     "Donkey Kong Country 2: Diddy's Kong Quest speedrun",
#     "Resident Evil Zero inventory management tips",
#     "Final Fantasy XIII paradigm shifts explained",
#     "Age of Empires II strategies",
#     "StarCraft gameplay",
#     "Command & Conquer: Red Alert mission walkthroughs",
#     "Diablo II character builds",
#     "Warcraft III: Reign of Chaos custom maps",
#     "EverQuest classic raids",
#     "Counter-Strike 1.6 competitive matches",
#     "Baldur's Gate character creation",
#     "Half-Life speedrun",
#     "The Sims cheat codes",
#     "Ultima Online player housing",
#     "Deus Ex storyline analysis",
#     "Fallout 2 tips and tricks",
#     "Warhammer 40,000: Dawn of War tactics",
#     "Diablo character classes compared",
#     "Heroes of Might and Magic III strategy guide",
#     "Commandos: Behind Enemy Lines mission strategies",
#     "Quake III Arena frag compilation",
#     "Star Wars: Knights of the Old Republic walkthrough",
#     "Sid Meier's Civilization III diplomacy tips",
#     "Red Alert 2 Soviet campaign playthrough",
#     "EverQuest II questing guide",
#     "Age of Mythology god powers explained",
#     "Diablo II: Lord of Destruction rune words",
#     "Warcraft II: Tides of Darkness Orc campaign walkthrough",
#     "The Elder Scrolls III: Morrowind mod showcase",
#     "Max Payne bullet time mechanics",
#     "RollerCoaster Tycoon park design",
#     "Warcraft III: The Frozen Throne competitive strategies",
#     "Command & Conquer: Generals base building tips",
#     "Neverwinter Nights character progression",
#     "Counter-Strike: Source weapon spray patterns",
#     "Age of Empires civilization overviews",
#     "Diablo III endgame content",
#     "Guild Wars elite areas",
#     "Red Alert 2 Yuri's Revenge expansion tactics",
#     "Fallout Tactics squad management",
#     "Warcraft III custom campaigns",
#     "The Sims 2 expansion pack reviews",
#     "Star Wars Galaxies crafting system",
#     "Command & Conquer: Red Alert 2 mods",
#     "Deus Ex: Invisible War plot analysis",
#     "Myst puzzle solutions",
#     "Age of Mythology: The Titans campaign playthrough",
#     "SimCity 3000 city planning tips",
#     "Heroes of Might and Magic IV hero builds",
#     "Warcraft II: Beyond the Dark Portal human campaign guide",
#     "The Elder Scrolls IV: Oblivion vampire guide",
#     "Max Payne 2: The Fall of Max Payne story recap",
#     "Rise of Nations resource management strategies",
    # "Valorant strategies",
    # "Overwatch hero guides",
    # "CS:GO pro matches",
    # "GoldenEye multiplayer tips",
    # "Call of Duty loadouts",
    # "Halo campaign walkthrough",
    # "Team Fortress 2 tactics",
    # "Apex Legends tier list",
    # "Rainbow Six Siege strategies",
    # "Destiny 2 PvP gameplay",
    # "Battlefield V tactics",
    # "Quake Live tips",
    # "Titanfall 2 movement",
    # "Doom speedrun",
    # "Half-Life mods",
    # "Gears of War",
    # "Borderlands 3 builds",
    # "CS 1.6 callouts",
    # "Overwatch esports",
    # "Valorant agents",
    # "Warzone landing spots",
    # "GoldenEye missions",
    # "Destiny 2 raids",
    # "Halo 2 glitches",
    # "Team Fortress Classic",
    # "Quake III tricks",
    # "Apex Legends ranked",
    # "Rainbow Six loadouts",
    # "Doom secrets",
    # "Half-Life 2 analysis",
    # "CS: Source matches",
    # "Overwatch combos",
    # "Valorant maps",
    # "CoD: Cold War loadouts",
    # "GoldenEye speedrun",
    # "Destiny 2 exotics",
    # "Halo 3 skulls",
    # "Team Fortress trading",
    # "Quake Champions abilities",
    # "Apex Legends loot",
    # "Rainbow Six counters",
    # "Doom Eternal bosses",
    # "CS:GO grenades",
    # "Overwatch lore",
    # "Valorant aiming drills",
    # "CoD 2v2 strategies",
    # "GoldenEye cheats",
    # "Destiny 2 Trials",
    #     "Best Game Boy games",
    # "Nintendo Switch accessories",
    # "Steam Deck release date",
    # "Game Boy color mods",
    # "Switch Lite vs. OG Switch",
    # "Top Game Boy emulators",
    # "Steam Deck performance",
    # "Nintendo Switch exclusives",
    # "Game Boy homebrew games",
    # "Switch OLED model",
    # "Game Boy backlight mod",
    # "Steam Deck pre-order",
    # "Nintendo Switch hacks",
    # "Game Boy Advance SP",
    # "Switch battery life",
    # "Game Boy collecting guide",
    # "Steam Deck storage options",
    # "Nintendo Switch online",
    # "Game Boy screen replacement",
    # "Switch multiplayer games",
    # "Steam Deck vs. Switch",
    # "Game Boy modding tutorial",
    # "Switch system updates",
    # "Game Boy EverDrive",
    # "Steam Deck game compatibility",
    # "Nintendo Switch parental controls",
    # "Game Boy emulator setup",
    # "Switch eShop deals",
    # "Game Boy camera games",
    # "Steam Deck hardware specs",
    # "Nintendo Switch Lite colors",
    # "Game Boy battery replacement",
    # "Switch game recommendations",
    # "Game Boy music mods",
    # "Steam Deck custom firmware",
    # "Nintendo Switch system transfer",
    # "Game Boy flash carts",
    # "Switch online multiplayer",
    # "Game Boy homebrew development",
    # "Steam Deck controller options",
    # "Nintendo Switch homebrew scene",
    # "Game Boy game preservation",
    # "Switch game updates",
    # "Game Boy clone consoles",
    # "Steam Deck vs. handheld PCs",
    # "Nintendo Switch cloud saves",
    # "Game Boy emulator legality",
    # "Switch hidden features",
    # "Game Boy collectible variations",
    # "Steam Deck performance benchmarks",
    # "Nintendo Switch joy-con drift",
    # "Game Boy screen protectors",
    #   "Witcher 3 vs. Skyrim",
    # "Best fantasy RPGs",
    # "Dragon Age Origins",
    # "Final Fantasy VII",
    # "Diablo 2 remastered",
    # "Elder Scrolls series",
    # "Mass Effect trilogy",
    # "Gothic vs. Risen",
    # "World of Warcraft",
    # "Dark Souls series",
    # "Baldur's Gate III",
    # "Fable franchise",
    # "Kingdom Come Deliverance",
    # "Divinity Original Sin",
    # "Path of Exile",
    # "Neverwinter Nights",
    # "Pillars of Eternity",
    # "Fallout New Vegas",
    # "Monster Hunter World",
    # "Chrono Trigger vs. Final Fantasy VI",
    # "Dragon's Dogma",
    # "The Legend of Zelda",
    # "Titan Quest",
    # "Mass Effect vs. KOTOR",
    # "Dragon Age Inquisition",
    # "Witcher series",
    # "Skyrim vs. Fallout 4",
    # "Diablo 3 vs. PoE",
    # "Elder Scrolls Online",
    # "Final Fantasy XIV",
    # "Gothic vs. Gothic II",
    # "Kingdoms of Amalur",
    # "Dragon Quest series",
    #"Dark Souls vs. Bloodborne",
    #"Neverwinter vs. ESO",
    #"Pillars of Eternity II",
    #"Divinity vs. Baldur's Gate",
    #"Dragon Age vs. Mass Effect",
    #"Fable II vs. Fable III",
    #"Witcher 2 vs. Witcher 3",
    #"Fallout vs. The Outer Worlds",
    #"Zelda: Breath of the Wild",
    #"Final Fantasy X",
    #"Diablo II vs. Diablo III",
    #"World of Warcraft vs. FFXIV",
    #"Path of Exile vs. Diablo",
    #"Dragon Age vs. Skyrim",
    #"Neverwinter Nights vs. BG",
    #"Mass Effect vs. Witcher",
    #"Gothic II vs. Gothic III",
    #"Elder Scrolls vs. Fallout",
    #"Divinity OS vs. DOS II",

    #"Best indie games",
    #"Open-world RPGs",
    #"Action-adventure games",
    #"Platformers on Switch",
    #"Survival horror titles",
    #"Tactical strategy games",
    #"Metroidvania recommendations",
    #"Co-op multiplayer games",
    #"Turn-based RPGs",
    #"Stealth games for PC",
    #"Point-and-click adventures",
    #"Racing simulators",
    #"Sandbox games on Steam",
    #"VR horror experiences",
    #"Puzzle-platformers",
    #"Simulation games 2021",
    #"First-person shooters",
    #"Exploration games",
    #"Hack and slash titles",
    #"JRPGs for beginners",
    #"Sports games on Xbox",
    #"Character action games",
    #"Strategy games on PS4",
    #"Visual novels on Steam",
    #"Horror games for VR",
    #"Retro-style indie games",
    #"Online multiplayer RPGs",
    #"Sci-fi adventure games",
    #"Farming simulators",
    #"Real-time strategy games",
    #"Post-apocalyptic games",
    #"Pixel art platformers",
    #"Steampunk-themed titles",
    #"Multiplayer party games",
    #"Action RPGs on Switch",
    #"Indie games on PS5",
    #"Mystery detective games",
    #"Historical strategy games",
    #"Cyberpunk RPGs",
    #"Psychological horror titles",
    #"Roguelike games on Steam",
    #"Story-driven adventures",
    #"Exploration games for PC",
    #"Survival sandbox titles",
    #"Platformers with pixel art",
    #"Stealth action games",
    #"Space exploration sims",
    #"Action-adventure games on PS4",
    #"Indie games on Xbox Game Pass",
    #"Zombie survival games",
    #"Sci-fi shooters",
    #"Classic point-and-click adventures",
    #"RPGs with character creation",
    #"Puzzle games on mobile",
    #"Strategy games with multiplayer",
    #"Fantasy action RPGs",
    #"Simulation games on Nintendo Switch",
    #"Racing games with realistic physics",
    #"Metroidvania games on PC",
    #"Horror games on PSVR",
    #"Indie platformers on Steam",
    #"Co-op survival games",
    #"Action-adventure games on Xbox",
    #"2D puzzle-platformers",
    #"Survival horror games on PC",
    #"Turn-based strategy games",
    #"JRPGs on Nintendo Switch",
    #"Sports simulation games",
    #"Open-world games with crafting",
    #"Stealth games with compelling stories",
    #"Sci-fi RPGs on Steam",
    #"Pixel art adventure games",
    #"Realistic racing simulators",
    #"Strategy games on mobile",
    #"Indie games on PSVR",
    #"Exploration games with beautiful worlds",
    #"Post-apocalyptic RPGs",
    #"Puzzle games with unique mechanics",
    #"Strategy games on Xbox Game Pass",
    # "Retro-style platformers",
    # "Psychological thriller games",
    # "Action RPGs on PC",
    # "Indie games on Nintendo Switch",
    # "Survival sandbox games on Steam",
    # "Platformers with challenging gameplay",
    # "Stealth games with open-ended levels",
    # "Space exploration games on PC",
    # "Action-adventure games on Steam",
    # "Indie games on Xbox Series X",
    # "Zombie survival games on PS4",
    # "Sci-fi shooters on Xbox",
    # "Classic adventure games",
    # "RPGs with deep customization",
    # "Puzzle games with atmospheric worlds",
    # "Strategy games on PS5",
    # "Fantasy RPGs with epic quests",
    # "Simulation games on Steam",
    # "Racing games with online multiplayer",
    # "Metroidvania games on Xbox Game Pass",
    # "Horror games with psychological tension",
    # "Indie platformers on Nintendo Switch",
    # "Co-op survival sandbox games",
    # "Action-adventure games on PS5",
    # "2D puzzle games",
    # "Survival horror games on Xbox",
    # "Turn-based tactics games",
    # "JRPGs with captivating stories",
    # "Sports games on PC",
    # "Open-world RPGs with rich lore",
    # "Stealth games with advanced AI",
    # "Sci-fi RPGs with immersive worlds",
    # "Pixel art games with nostalgia",
    # "Realistic racing games on PS4",
    # "Strategy games with deep gameplay",
    # "Indie games on Steam",

    "Best mobile games",
    "Diablo Immortal release date",
    "Genshin Impact gameplay",
    "Mobile RPG recommendations",
    "Kardashian game review",
    "Disney Sorcerer Arena tips",
    "Popular mobile MMOs",
    "Free-to-play mobile games",
    "Diablo Immortal classes",
    "Genshin Impact character guide",
    "Mobile strategy games",
    "Kardashian game cheats",
    "Disney Sorcerer Arena characters",
    "Mobile gacha games",
    "Diablo Immortal beta",
    "Genshin Impact elemental reactions",
    "Mobile puzzle games",
    "Kardashian game energy cheats",
    "Disney Sorcerer Arena strategies",
    "Mobile MMORPGs",
    "Diablo Immortal gameplay",
    "Genshin Impact tier list",
    "Mobile action games",
    "Kardashian game hacks",
    "Disney Sorcerer Arena team building",
    "Mobile idle games",
    "Diablo Immortal character classes",
    "Genshin Impact exploration",
    "Mobile racing games",
    "Kardashian game fashion tips",
    "Disney Sorcerer Arena events",
    "Mobile tower defense games",
    "Diablo Immortal multiplayer",
    "Genshin Impact open-world",
    "Mobile sports games",
    "Kardashian game dating tips",
    "Disney Sorcerer Arena guilds",
    "Mobile simulation games",
    "Diablo Immortal beta test",
    "Genshin Impact co-op",
    "Mobile adventure games",
    "Kardashian game money cheats",
    "Disney Sorcerer Arena PvP",
    "Mobile card games",
    "Diablo Immortal classes overview",
    "Genshin Impact boss fights",
    "Mobile casino games",
    "Kardashian game relationship guide",
    "Disney Sorcerer Arena best teams",
    "Mobile rhythm games",
]
